=== LearnNetZero/LearnHPB/XML/LearnHPB/IDREF1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:test="http://www.learnhpb.org/schemas/test" targetNamespace="http://www.learnhpb.org/schemas/test" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="component" type="test:componentType" maxOccurs="99"/>
				
			
				<xsd:element name="list" type="test:listType"/>  
				
				<xsd:element name="order" type="test:orderDetails"/>
				<xsd:element name="orderlist" type="test:orderLists"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	
	
  <xsd:complexType name="listType">  
     <xsd:sequence>  
      <xsd:element name="def" type="test:componentDefType" minOccurs="0" maxOccurs="unbounded"/>  
     </xsd:sequence>  
  </xsd:complexType>  
  
  
  
	<xsd:complexType name="componentType">
		<xsd:sequence>
			<xsd:element name="componentIDREF" type="xsd:IDREF"/>
		</xsd:sequence>
	</xsd:complexType>
	
	
	
	<xsd:complexType name="componentDefType">
		<xsd:sequence>
			<xsd:element name="componentID" type="xsd:ID" maxOccurs="unbounded"/>
			<xsd:element name="componentName" type="xsd:string" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="orderDetails">
		<xsd:sequence>
			<xsd:element name="customerName" type="xsd:string"/>
			<xsd:element name="customerAddress" type="xsd:string"/>
			<xsd:element name="customerContact" type="xsd:string"/>
			<xsd:element name="orderIDREF" type="xsd:IDREF"/>
			<xsd:element name="orderIDREFS" type="xsd:IDREFS"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="orderLists">
		<xsd:sequence>
			<xsd:element name="orderID" type="xsd:ID" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== LearnNetZero/LearnHPB/XML/LearnHPB/IDREF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?altova_sps IDREF1.sps?>
<dataset xmlns="http://www.learnhpb.org/schemas/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.learnhpb.org/schemas/test
IDREF1.xsd">
	<component>
		<componentIDREF>LT</componentIDREF>
	</component>
	<list>
		<def>
			<componentID>LT</componentID>
			<componentName>Lighting</componentName>
		</def>
		<def>
			<componentID>GN</componentID>
			<componentName>General</componentName>
		</def>
	</list>
	<order>
		<customerName>Test</customerName>
		<customerAddress>Test Address</customerAddress>
		<customerContact>12345678</customerContact>
		<orderIDREF>k1</orderIDREF>
		<orderIDREFS>k1 k2</orderIDREFS>
	</order>
	<orderlist>
		<orderID>k1</orderID>
		<orderID>k2</orderID>
	</orderlist>
</dataset>
