=== LearnNetZero/LearnHPB/XML/LearnHPB/learnHPBv2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
xmlns:hpb="http://www.learnhpb.org/schemas/learn-hpb" 
xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.learnhpb.org/schemas/learn-hpb" 
elementFormDefault="qualified" 
attributeFormDefault="unqualified">

	<element name="scenario">
		<complexType>
			<sequence>
				<element name="component" type="hpb:Tcomponent" maxOccurs="unbounded"/>
				<element name="systemList" type="hpb:TsystemList" maxOccurs="1"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="Tcomponent">
		<sequence>
			<element name="system-ref">
				<complexType>
					<attribute name="ref" type="IDREF" use="required"/>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<complexType name="TsystemList">
		<sequence>
			<element name="system" type="hpb:Tsystem" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Tsystem">
		<sequence>
			<element name="long-name" type="string"/>
		</sequence>
		<attribute name="id" type="ID" use="required"/>
	</complexType>
	<!--
	<element name="
anElement">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="otherText" type="string"/>
					<attribute name="myNote">
						<simpleType>
							<restriction base="NOTATION">
								<enumeration value="gif"/>
								<enumeration value="myNote"/>
							</restriction>
						</simpleType>
					</attribute>
				</extension>
			</simpleContent>
		</complexType>
	</element>
<complexType abstract="true" name="SystemBase">
  <sequence>
    <element name="long-name" type="string"/>
    <element name="code-name" type="string"/>
  </sequence>
</complexType>


<complexType name="System">
  <sequence>
    <element name="long-name" type="string"/>
    <element name="code-name" type="string"/>
  </sequence>
</complexType>


<complexType name="SystemEX">
  <sequence>
       <choice minOccurs="1" maxOccurs="1">
          <element name="General" type="string" />
          <element name="Envelope" type="string" />
          <element name="Lighting" type="string" />
        </choice>
  </sequence>
</complexType>

-->
</schema>

=== LearnNetZero/LearnHPB/XML/LearnHPB/LearnHPBv2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?altova_sps LearnHPBv2.sps?>
<scenario xmlns="http://www.learnhpb.org/schemas/learn-hpb" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.learnhpb.org/schemas/learn-hpb learnHPBv2.xsd">
	<component>
		<system-ref ref="HV"/>
	</component>
	<systemList>
		<system id="GN">
			<long-name>General</long-name>
		</system>
		<system id="HV">
			<long-name>HVAC</long-name>
		</system>
		<system id="EN">
			<long-name>Envelope </long-name>
		</system>
		<system id="LT">
			<long-name>Lighting</long-name>
		</system>
		<system id="DL">
			<long-name>Daylighting</long-name>
		</system>
	</systemList>
</scenario>
