=== LearnNetZero/LearnHPB/XML/LearnHPB/Lighting2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by Allan Abraham (Altova GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.learnhpb.org/schemas/hpb" targetNamespace="http://www.learnhpb.org/schemas/hpb" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Building">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="light" maxOccurs="unbounded"/>
				<xs:element ref="lampList" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="light">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lamp" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lampList">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Atom">
					<xs:sequence>
						<xs:element ref="lamp" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="lamp">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" type="xs:string" minOccurs="0"/>
				<xs:element name="wattage" type="xs:string" minOccurs="0"/>
				<xs:element name="lumens" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="lamp">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="wattage" type="xs:string" minOccurs="0"/>
			<xs:element name="lumens" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="abbr" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Atom">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="abbr" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Category">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Atom">
					<xs:sequence>
						<xs:element ref="Variable" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Variable">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Atom">
					<xs:sequence>
						<xs:choice>
							<xs:element name="Enum" type="TypeEnum"/>
							<xs:element name="Decimal" type="TypeDecimal"/>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="phase" type="ProjectPhase"/>
					<xs:attribute name="scope" type="Scope"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TypeDecimal">
		<xs:sequence>
			<xs:element name="value" type="xs:decimal" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="unit" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TypeEnum">
		<xs:sequence>
			<xs:element name="Option" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ProjectPhase">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1a"/>
			<xs:enumeration value="1b"/>
			<xs:enumeration value="1c"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Scope">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gui"/>
			<xs:enumeration value="input"/>
			<xs:enumeration value="output"/>
			<xs:enumeration value="equation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Variability">
		<xs:restriction base="xs:string">
			<xs:enumeration value="parameter"/>
			<xs:enumeration value="continuous"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== LearnNetZero/LearnHPB/XML/LearnHPB/Lighting2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Building xmlns="http://www.learnhpb.org/schemas/hpb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.learnhpb.org/schemas/hpb Lighting2.xsd">
	
	
	<light>
		<lamp name="T5-1"></lamp>
	</light>
	
	
	
	<lampList name="String" abbr="String">
	
		<lamp name="T5-1">
			<type>T5</type>
			<wattage>25</wattage>
			<lumens>2475</lumens>
		</lamp>
		
		<lamp id="xx2" name="T5-2">
			<type>T5</type>
			<wattage>28</wattage>
			<lumens>2725</lumens>
		</lamp>
		
	</lampList>


	
</Building>
